<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'grid' => array( 'dashboard-item4',
'dashboard-item3',
'dashboard-item2',
'dashboard-item1',
'dashboard-item' ),
'supertop' => array( 'logo',
'menu',
'simple_search',
'loginform_login',
'username_button' ),
'top' => array( 'breadcrumb',
'custom_button' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'dashboard-item4' => 'grid',
'dashboard-item3' => 'grid',
'dashboard-item2' => 'grid',
'dashboard-item1' => 'grid',
'dashboard-item' => 'grid',
'logo' => 'supertop',
'menu' => 'supertop',
'simple_search' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'breadcrumb' => 'top',
'custom_button' => 'top' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'menu' => 3,
'simple_search' => 3,
'username_button' => 3,
'loginform_login' => 3 ) ),
'itemsByType' => array( 'dashboard-item' => array( 'dashboard-item4',
'dashboard-item3',
'dashboard-item2',
'dashboard-item1',
'dashboard-item' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'custom_button' => array( 'custom_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => true,
'customButtons' => array( 'Request_Update_from_API' ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => true ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'dashboard',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'Request_Update_from_API' ) ),
'dashboard' => array( 'elements' => array( array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'dbo.bbc_art Chart',
'dashType' => 1,
'dashName' => 'dbo_bbc_art_Chart_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'bookmark' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'elementName' => 'dbo_bbc_art_Chart_chart',
'table' => 'dbo.bbc_art Chart',
'type' => 1,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'dbo.jaz_art Chart',
'dashType' => 1,
'dashName' => 'dbo_jaz_art_Chart_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'bookmark' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'elementName' => 'dbo_jaz_art_Chart_chart',
'table' => 'dbo.jaz_art Chart',
'type' => 1,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'dbo.may_art Chart',
'dashType' => 1,
'dashName' => 'dbo_may_art_Chart_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'bookmark' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'elementName' => 'dbo_may_art_Chart_chart',
'table' => 'dbo.may_art Chart',
'type' => 1,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'dbo.News Capstone_users Chart',
'dashType' => 1,
'dashName' => 'dbo_News_Capstone_users_Chart_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'users' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'elementName' => 'dbo_News_Capstone_users_Chart_chart',
'table' => 'dbo.News Capstone_users Chart',
'type' => 1,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'dbo.news capstone_audit Chart',
'dashType' => 1,
'dashName' => 'dbo_news_capstone_audit_Chart_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'user' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'elementName' => 'dbo_news_capstone_audit_Chart_chart',
'table' => 'dbo.news capstone_audit Chart',
'type' => 1,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ) ) ),
'dashSearch' => array( 'searchFields' => array( 'dbo_jaz_art_Chart_id' => array( array( 'field' => 'id',
'table' => 'dbo.jaz_art Chart' ) ),
'dbo_jaz_art_Chart_title' => array( array( 'field' => 'title',
'table' => 'dbo.jaz_art Chart' ) ),
'dbo_jaz_art_Chart_description' => array( array( 'field' => 'description',
'table' => 'dbo.jaz_art Chart' ) ),
'dbo_jaz_art_Chart_body' => array( array( 'field' => 'body',
'table' => 'dbo.jaz_art Chart' ) ),
'dbo_jaz_art_Chart_keywords' => array( array( 'field' => 'keywords',
'table' => 'dbo.jaz_art Chart' ) ),
'dbo_jaz_art_Chart_author' => array( array( 'field' => 'author',
'table' => 'dbo.jaz_art Chart' ) ),
'dbo_jaz_art_Chart_id_may' => array( array( 'field' => 'id_may',
'table' => 'dbo.jaz_art Chart' ) ),
'dbo_jaz_art_Chart_id_bbc' => array( array( 'field' => 'id_bbc',
'table' => 'dbo.jaz_art Chart' ) ),
'dbo_jaz_art_Chart_publishedTime' => array( array( 'field' => 'publishedTime',
'table' => 'dbo.jaz_art Chart' ) ),
'dbo_jaz_art_Chart_image_url' => array( array( 'field' => 'image_url',
'table' => 'dbo.jaz_art Chart' ) ),
'dbo_News_Capstone_users_Chart_ID' => array( array( 'field' => 'ID',
'table' => 'dbo.News Capstone_users Chart' ) ),
'dbo_News_Capstone_users_Chart_username' => array( array( 'field' => 'username',
'table' => 'dbo.News Capstone_users Chart' ) ),
'dbo_News_Capstone_users_Chart_password' => array( array( 'field' => 'password',
'table' => 'dbo.News Capstone_users Chart' ) ),
'dbo_News_Capstone_users_Chart_email' => array( array( 'field' => 'email',
'table' => 'dbo.News Capstone_users Chart' ) ),
'dbo_News_Capstone_users_Chart_fullname' => array( array( 'field' => 'fullname',
'table' => 'dbo.News Capstone_users Chart' ) ),
'dbo_News_Capstone_users_Chart_groupid' => array( array( 'field' => 'groupid',
'table' => 'dbo.News Capstone_users Chart' ) ),
'dbo_News_Capstone_users_Chart_active' => array( array( 'field' => 'active',
'table' => 'dbo.News Capstone_users Chart' ) ),
'dbo_News_Capstone_users_Chart_ext_security_id' => array( array( 'field' => 'ext_security_id',
'table' => 'dbo.News Capstone_users Chart' ) ),
'dbo_News_Capstone_users_Chart_two_factor' => array( array( 'field' => 'two_factor',
'table' => 'dbo.News Capstone_users Chart' ) ),
'dbo_News_Capstone_users_Chart_reset_token' => array( array( 'field' => 'reset_token',
'table' => 'dbo.News Capstone_users Chart' ) ),
'dbo_News_Capstone_users_Chart_reset_date' => array( array( 'field' => 'reset_date',
'table' => 'dbo.News Capstone_users Chart' ) ),
'dbo_news_capstone_audit_Chart_id' => array( array( 'field' => 'id',
'table' => 'dbo.news capstone_audit Chart' ) ),
'dbo_news_capstone_audit_Chart_datetime' => array( array( 'field' => 'datetime',
'table' => 'dbo.news capstone_audit Chart' ) ),
'dbo_news_capstone_audit_Chart_ip' => array( array( 'field' => 'ip',
'table' => 'dbo.news capstone_audit Chart' ) ),
'dbo_news_capstone_audit_Chart_user' => array( array( 'field' => 'user',
'table' => 'dbo.news capstone_audit Chart' ) ),
'dbo_news_capstone_audit_Chart_table' => array( array( 'field' => 'table',
'table' => 'dbo.news capstone_audit Chart' ) ),
'dbo_news_capstone_audit_Chart_action' => array( array( 'field' => 'action',
'table' => 'dbo.news capstone_audit Chart' ) ),
'dbo_news_capstone_audit_Chart_description' => array( array( 'field' => 'description',
'table' => 'dbo.news capstone_audit Chart' ) ),
'dbo_bbc_art_Chart_id' => array( array( 'field' => 'id',
'table' => 'dbo.bbc_art Chart' ) ),
'dbo_bbc_art_Chart_title' => array( array( 'field' => 'title',
'table' => 'dbo.bbc_art Chart' ) ),
'dbo_bbc_art_Chart_description' => array( array( 'field' => 'description',
'table' => 'dbo.bbc_art Chart' ) ),
'dbo_bbc_art_Chart_body' => array( array( 'field' => 'body',
'table' => 'dbo.bbc_art Chart' ) ),
'dbo_bbc_art_Chart_keywords' => array( array( 'field' => 'keywords',
'table' => 'dbo.bbc_art Chart' ) ),
'dbo_bbc_art_Chart_author' => array( array( 'field' => 'author',
'table' => 'dbo.bbc_art Chart' ) ),
'dbo_bbc_art_Chart_publishedTime' => array( array( 'field' => 'publishedTime',
'table' => 'dbo.bbc_art Chart' ) ),
'dbo_may_art_Chart_id' => array( array( 'field' => 'id',
'table' => 'dbo.may_art Chart' ) ),
'dbo_may_art_Chart_title' => array( array( 'field' => 'title',
'table' => 'dbo.may_art Chart' ) ),
'dbo_may_art_Chart_description' => array( array( 'field' => 'description',
'table' => 'dbo.may_art Chart' ) ),
'dbo_may_art_Chart_body' => array( array( 'field' => 'body',
'table' => 'dbo.may_art Chart' ) ),
'dbo_may_art_Chart_keywords' => array( array( 'field' => 'keywords',
'table' => 'dbo.may_art Chart' ) ),
'dbo_may_art_Chart_author' => array( array( 'field' => 'author',
'table' => 'dbo.may_art Chart' ) ),
'dbo_may_art_Chart_publishedTime' => array( array( 'field' => 'publishedTime',
'table' => 'dbo.may_art Chart' ) ) ),
'allSearchFields' => array( 'dbo_jaz_art_Chart_id',
'dbo_jaz_art_Chart_title',
'dbo_jaz_art_Chart_description',
'dbo_jaz_art_Chart_body',
'dbo_jaz_art_Chart_keywords',
'dbo_jaz_art_Chart_author',
'dbo_jaz_art_Chart_id_may',
'dbo_jaz_art_Chart_id_bbc',
'dbo_jaz_art_Chart_publishedTime',
'dbo_jaz_art_Chart_image_url',
'dbo_News_Capstone_users_Chart_ID',
'dbo_News_Capstone_users_Chart_username',
'dbo_News_Capstone_users_Chart_password',
'dbo_News_Capstone_users_Chart_email',
'dbo_News_Capstone_users_Chart_fullname',
'dbo_News_Capstone_users_Chart_groupid',
'dbo_News_Capstone_users_Chart_active',
'dbo_News_Capstone_users_Chart_ext_security_id',
'dbo_News_Capstone_users_Chart_two_factor',
'dbo_News_Capstone_users_Chart_reset_token',
'dbo_News_Capstone_users_Chart_reset_date',
'dbo_news_capstone_audit_Chart_id',
'dbo_news_capstone_audit_Chart_datetime',
'dbo_news_capstone_audit_Chart_ip',
'dbo_news_capstone_audit_Chart_user',
'dbo_news_capstone_audit_Chart_table',
'dbo_news_capstone_audit_Chart_action',
'dbo_news_capstone_audit_Chart_description',
'dbo_bbc_art_Chart_id',
'dbo_bbc_art_Chart_title',
'dbo_bbc_art_Chart_description',
'dbo_bbc_art_Chart_body',
'dbo_bbc_art_Chart_keywords',
'dbo_bbc_art_Chart_author',
'dbo_bbc_art_Chart_publishedTime',
'dbo_may_art_Chart_id',
'dbo_may_art_Chart_title',
'dbo_may_art_Chart_description',
'dbo_may_art_Chart_body',
'dbo_may_art_Chart_keywords',
'dbo_may_art_Chart_author',
'dbo_may_art_Chart_publishedTime' ),
'googleLikeFields' => array(  ) ) );
			$pageArray = array( 'id' => 'dashboard',
'type' => 'dashboard',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'grid' => array( 'modelId' => 'dashboard-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c3',
'colspan' => 1 ),
array( 'cell' => 'c6' ),
array( 'cell' => 'c' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 3 ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'dashboard-item4' ),
'align' => 'center' ),
'c3' => array( 'model' => 'c1',
'items' => array( 'dashboard-item3' ),
'align' => 'center' ),
'c4' => array( 'model' => 'c1',
'items' => array( 'dashboard-item2' ),
'align' => 'center' ),
'c5' => array( 'model' => 'c1',
'items' => array( 'dashboard-item1' ),
'align' => 'center' ),
'c6' => array( 'model' => 'c1',
'items' => array( 'dashboard-item' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'topbar-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'dashboard-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'breadcrumb' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'custom_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'dashboard-item4' => array( 'type' => 'dashboard-item',
'table' => 'dbo.may_art Chart',
'dashType' => 1,
'dashName' => 'dbo_may_art_Chart_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'bookmark' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'dashboard-item3' => array( 'type' => 'dashboard-item',
'table' => 'dbo.bbc_art Chart',
'dashType' => 1,
'dashName' => 'dbo_bbc_art_Chart_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'bookmark' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'dashboard-item2' => array( 'type' => 'dashboard-item',
'table' => 'dbo.news capstone_audit Chart',
'dashType' => 1,
'dashName' => 'dbo_news_capstone_audit_Chart_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'user' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'dashboard-item1' => array( 'type' => 'dashboard-item',
'table' => 'dbo.News Capstone_users Chart',
'dashType' => 1,
'dashName' => 'dbo_News_Capstone_users_Chart_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'users' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'dashboard-item' => array( 'type' => 'dashboard-item',
'table' => 'dbo.jaz_art Chart',
'dashType' => 1,
'dashName' => 'dbo_jaz_art_Chart_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'bookmark' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login' ),
'custom_button' => array( 'eventId' => 'Request_Update_from_API',
'label' => array( 'text' => 'Request Update from API',
'type' => 0 ),
'type' => 'custom_button',
'buttonStyle' => 'success' ) ),
'dbProps' => array(  ),
'version' => 14,
'pageAlign' => 'center',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>