<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'portrait',
'scale' => 100 ),
'details' => array( 'dbo.may_art' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'dbo.bbc_art' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'master' => array( 'dbo.bbc_art Chart' => array( 'preview' => false ),
'dbo.may_art Chart' => array( 'preview' => false ) ),
'fields' => array( 'gridFields' => array( 'imageView',
'title',
'description',
'body',
'keywords',
'author',
'publishedTime',
'id_may',
'id_bbc' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'imageView' => array( 'integrated_edit_field' ),
'title' => array( 'integrated_edit_field1' ),
'description' => array( 'integrated_edit_field2' ),
'body' => array( 'integrated_edit_field3' ),
'keywords' => array( 'integrated_edit_field4' ),
'author' => array( 'integrated_edit_field5' ),
'publishedTime' => array( 'integrated_edit_field8' ),
'id_may' => array( 'integrated_edit_field9' ),
'id_bbc' => array( 'integrated_edit_field10' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'top' => array( 'view_header' ),
'grid' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field',
'integrated_edit_field9',
'snippet',
'custom_button',
'image',
'snippet1',
'custom_button1',
'image1',
'text',
'integrated_edit_field10' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'view_header' => 'top',
'integrated_edit_field1' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field9' => 'grid',
'snippet' => 'grid',
'custom_button' => 'grid',
'image' => 'grid',
'snippet1' => 'grid',
'custom_button1' => 'grid',
'image1' => 'grid',
'text' => 'grid',
'integrated_edit_field10' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'snippet' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'custom_button' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'image' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'snippet1' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'custom_button1' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'image1' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'text' => array( 'location' => 'grid',
'cellId' => 'c14' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c5' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10' ),
'view_pdf' => array( 'view_pdf' ),
'snippet' => array( 'snippet',
'snippet1' ),
'image' => array( 'image',
'image1' ),
'text' => array( 'text' ),
'custom_button' => array( 'custom_button',
'custom_button1' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0,
1,
2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1,
2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1,
2 ),
'rows' => array( 1,
2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'text' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0,
1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'image' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 2,
3 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'image1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0,
1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c9' => array( 'cols' => array( 2,
3 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ) ),
'width' => 4,
'height' => 6 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => true,
'customButtons' => array( 'BBC_REDIRECT',
'MAY_REDIRECT' ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'BBC_REDIRECT',
'MAY_REDIRECT' ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3',
'rowspan' => 3 ),
array( 'cell' => 'c4',
'colspan' => 2 ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5',
'colspan' => 2,
'rowspan' => 2 ),
array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c14',
'colspan' => 4 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8',
'colspan' => 2 ),
array( 'cell' => 'c11',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7',
'colspan' => 2,
'rowspan' => 1 ),
array( 'cell' => 'c9',
'colspan' => 2,
'rowspan' => 1 ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field8' ) ),
'c' => array( 'model' => 'c3',
'items' => array(  ),
'align' => 'center',
'orientation' => 'vertical' ),
'c1' => array( 'model' => 'c3',
'items' => array(  ),
'align' => 'center',
'orientation' => 'vertical' ),
'c2' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field' ),
'align' => 'center',
'orientation' => 'vertical' ),
'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field9' ) ),
'c7' => array( 'model' => 'c3',
'items' => array( 'snippet',
'custom_button' ),
'align' => 'center',
'bold' => true ),
'c8' => array( 'model' => 'c3',
'items' => array( 'image' ),
'align' => 'center' ),
'c9' => array( 'model' => 'c3',
'items' => array( 'snippet1',
'custom_button1' ),
'align' => 'center',
'padding' => array( 'bottom' => '40px' ),
'bold' => true ),
'c11' => array( 'model' => 'c3',
'items' => array( 'image1' ),
'align' => 'center' ),
'c14' => array( 'model' => 'c3',
'items' => array( 'text' ),
'align' => 'center' ),
'c5' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field10' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header',
'title' => array( 'page' => 'view',
'table' => 'dbo.jaz_art',
'type' => 7 ) ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit',
'view_pdf' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field' => array( 'field' => 'imageView',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'imageView',
'table' => 'dbo.jaz_art',
'type' => 3 ) ),
'integrated_edit_field1' => array( 'field' => 'title',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'description',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'body',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'keywords',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'author',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'publishedTime',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'view_pdf' => array( 'type' => 'view_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ) ),
'snippet' => array( 'eventId' => 'BBC_SNIPPET',
'label' => array( 'text' => 'BBC SNIPPET',
'type' => 0 ),
'type' => 'snippet',
'color' => '#ffffff',
'background' => '#c66969' ),
'snippet1' => array( 'eventId' => 'AL_MAYADEEN_SNIPPET',
'label' => array( 'text' => 'AL MAYADEEN SNIPPET',
'type' => 0 ),
'type' => 'snippet',
'color' => '#ffffff',
'background' => '#8e8282' ),
'image' => array( 'type' => 'image',
'image' => array( 'image' => 'BBC_News-Logo.wine.png',
'source' => 2 ),
'width' => '150px',
'height' => '100px' ),
'image1' => array( 'type' => 'image',
'image' => array( 'image' => 'AlMayadeen.png',
'source' => 2 ),
'width' => '150px',
'height' => '100px' ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'RELATED',
'type' => 0 ),
'editedByRte' => false,
'bold' => true ),
'custom_button' => array( 'eventId' => 'BBC_REDIRECT',
'label' => array( 'text' => 'Check',
'type' => 0 ),
'type' => 'custom_button',
'buttonStyle' => 'primary',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  border-radius: 15px;
}
' ),
'custom_button1' => array( 'eventId' => 'MAY_REDIRECT',
'label' => array( 'text' => 'Check',
'type' => 0 ),
'type' => 'custom_button',
'buttonStyle' => 'primary',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  border-radius: 15px;
}
' ),
'integrated_edit_field9' => array( 'field' => 'id_may',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'id_may',
'table' => 'dbo.jaz_art',
'type' => 3 ) ),
'integrated_edit_field10' => array( 'field' => 'id_bbc',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'id_bbc',
'table' => 'dbo.jaz_art',
'type' => 3 ) ) ),
'dbProps' => array(  ),
'version' => 14,
'pageWidth' => 'full',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'pageCSS' => ' /* Style for the popup */
    .popup {
      display: none;
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      padding: 20px;
      background-color: #fff;
      border: 1px solid #ccc;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      z-index: 1000;
      width: 1000px; /* Adjust the width as needed */
      height: 1000px; /* Adjust the height as needed */
    }

    /* Style for the dismiss button */
    .dismiss-btn {
      background-color: #007bff;
      color: #fff;
      border: none;
      padding: 10px 20px;
      cursor: pointer;
    }

    /* Style for the iframe */
    .popup iframe {
      width: 100%;
      height: 100%;
      border: none;
    }',
'listTotals' => 1 );
		?>