<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '00',
'codeField' => '˂Create new˃',
'emailField' => 'email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'phoneField' => '˂Create new˃',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset_token',
'table' => array( 'connId' => 'News_at_192_168_1_225',
'table' => 'dbo.News Capstone_users' ),
'twoFactorField' => 'two_factor',
'userGroupField' => 'username',
'usernameField' => 'username',
'userpicField' => 'userpic' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'B32IzygFFL99vFgl0ELO',
'JWTSecret' => 'JTHtmnDjmq89f1zum2gV',
'forceExpire' => true,
'keepAlive' => false,
'warnExpire' => true ),
'registration' => array( 'passwordValidation' => array( 'strong' => true,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => true ),
'remindMethod' => 1,
'hashAlgorithm' => 0,
'adminEmail' => 'mzaitoun@protel.com.lb',
'changePasswordPage' => true,
'changePwdPage' => false,
'hashPassword' => true,
'notifyAdmin' => true,
'notifyUser' => true,
'registerPage' => true,
'remindPage' => false,
'remindPasswordPage' => true,
'sendActivationLink' => true ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => 'almaarefproject@gmail.com',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'smtp.gmail.com',
'SMTPPort' => 587,
'SMTPUser' => 'almaarefproject@gmail.com',
'SMTPPassword' => 'bkjk ohhi zcci fflq',
'securityProtocol' => 2 ),
'advancedSecurity' => array( 'allowGuestLogin' => true,
'tables' => array( 'dbo.News Capstone_users' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'dbo.bbc_art' => array( 'mainOwnerIDField' => 'id',
'securityOption' => 0,
'userOwnerIDField' => 'ID' ),
'dbo.jaz_art' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'dbo.may_art' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ) ) ),
'auditAndLocking' => array( 'loggingTable' => array( 'connId' => 'News_at_192_168_1_225',
'table' => 'dbo.news capstone_audit' ),
'lockingTable' => array( 'connId' => 'News_at_192_168_1_225',
'table' => 'dbo.news capstone_locking' ),
'tables' => array( 'dbo.News Capstone_users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'dbo.bbc_art' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'dbo.jaz_art' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'dbo.may_art' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ) ),
'loggingMode' => 1,
'loggingFile' => 'audit.log',
'logSecurityActions' => true,
'lockAfterUnsuccessfulLogin' => true,
'enableLocking' => true ),
'twoFactorSettings' => array( 'available' => true,
'required' => false,
'enable' => false,
'remember' => true,
'types' => array( 'email' => true,
'totp' => false ),
'twoFactorField' => 'two_factor',
'emailField' => 'email',
'phoneField' => '˂Create new˃',
'codeField' => '˂Create new˃',
'projectName' => 'News Capstone' ),
'projectName' => 'News Capstone',
'loginDataSource' => 'dbo.News Capstone_users',
'loginForm' => 0,
'dynamicPermissions' => true,
'dpTablePrefix' => 'dbo.News Capstone',
'dpTableConnId' => 'News_at_192_168_1_225',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '00',
'codeField' => '˂Create new˃',
'emailField' => 'email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'phoneField' => '˂Create new˃',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset_token',
'table' => array( 'connId' => 'News_at_192_168_1_225',
'table' => 'dbo.News Capstone_users' ),
'twoFactorField' => 'two_factor',
'userGroupField' => 'username',
'usernameField' => 'username',
'userpicField' => 'userpic' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '00' ),
'notifications' => array(  ) );
?>